Repository paduszyk/ILThermoML, pull requests merged in 2025-03, with the labels that each got.

#57 Dataset population progress monitoring
  pyproject.toml
  src/ilthermoml/dataset.py
  uv.lock
Labels: enhancement

#75 Enable silent joblib cache logging via environment variable
  src/ilthermoml/memory.py
Labels: enhancement

#78 Add GitHub Actions workflow for label synchronization
  .github/workflows/labels.yml
Labels: priority: low, status: review needed, status: available, type: maintenance

#81 Add ionic liquid handling to Entry and Dataset classes
  src/ilthermoml/chemistry.py
  src/ilthermoml/dataset.py
  tests/test_dataset.py
Labels: status: review needed, status: available, type: enhancement, priority: high
